### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Nanoliz11** [H4xton/TikTok-Reportation-Bot#1]
Hi there,

I get these: 

Traceback (most recent call last):
  File "C:\Users\Nolan\Desktop\LOOPOLE\trial\TikTok-Reportation-Bot\bot.py", line 61, in <module>     
    while True: TikTok.sendreport(0,videoid,videolink)
  File "C:\Users\Nolan\Desktop\LOOPOLE\trial\TikTok-Reportation-Bot\bot.py", line 53, in sendreport   
    receiveresponse = response.json()['errMsg']
  File "C:\Users\Nolan\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", 
line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Nolan\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Nolan\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Nolan\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\Nolan\Desktop\LOOPOLE\trial\TikTok-Reportation-Bot>

Any help?

**Comment by H4xton** [comment]
Install requirements
